platform :ios,'9.0'
target 'AR-Call-Tutorial-iOS' do
    
use_frameworks!

pod 'ARtcKit_iOS', '~> 4.1.1.0'
pod 'ARtmKit_iOS', '~> 1.0.1.2'
pod 'Bugly', '~> 2.5.2'
pod 'SVProgressHUD', '~> 2.2.5'
pod 'Masonry'

end
